export const accountList =  [
    {value: "威富通APP支付", name: "威富通APP支付"},
    {value: "银商APP支付", name: "银商APP支付"},
    {value: "支付宝直连-优品珠宝", name: "支付宝直连-优品珠宝"},
    {value: "支付宝直连-优品资信", name: "支付宝直连-优品资信"},
    {value: "银联云闪付", name: "银联云闪付"},
    {value: "支付宝直连-电子商务", name: "支付宝直连-电子商务"},
    {value: "支付宝直连-融资租赁", name: "支付宝直连-融资租赁"},
    {value: "支付宝直连-电子商务-dzsw2030@qnvip.com", name: "支付宝直连-电子商务-dzsw2030@qnvip.com"},
    {value: "支付宝小程序-电子商务", name: "支付宝小程序-电子商务"},
    {value: "微信-电子商务", name: "微信-电子商务"},
    {value: "支付宝直连-电子商务-dzsw2020@qnvip.com", name: "支付宝直连-电子商务-dzsw2020@qnvip.com"},
    {value: "支付宝小程序-融资租赁-rzzl@qnvip.com", name: "支付宝小程序-融资租赁-rzzl@qnvip.com"},
    {value: "支付宝小程序-甬易生活-yongyishenghuo@qnvip.com", name: "支付宝小程序-甬易生活-yongyishenghuo@qnvip.com"},
    {value: "支付宝小程序-信天下-xtx2022@163.com", name: "支付宝小程序-信天下-xtx2022@163.com"},
    {value: "微信-电子商务-青年优品", name: "微信-电子商务-青年优品"},
    {value: "银商分账支付-电子商务", name: "银商分账支付-电子商务"},
  ]
  
  export const amountTypeList = [
    {value: 1, name: '还款计划'},
    {value: 2, name: '其他费用'},
    {value: 3, name: '买断费用'},
    {value: 4, name: '保证金'},
    {value: 5, name: '全款'},
    {value: 6, name: '续租'},
    {value: 7, name: '归还'},
    {value: 8, name: '大数据报告'},
    {value: 9, name: '全款商品'},
    {value: 10, name: '后台线下还款'},
    {value: 11, name: '微信邀请活动提现'},
    {value: 12, name: '积分商品'},
    {value: 13, name: '微信砍价活动提现'},
    {value: 16, name: '短租租金'},
    {value: 23, name: '保证金抵扣'},
    {value: 24, name: '部分还款(小程序)'},
    {value: 25, name: '部分还款(后台)'},
  ]
  